C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/contact/ HTTP/1.1" 200 16415
"POST /Accounts/contact_view HTTP/1.1" 200 56
- Broken pipe from ('127.0.0.1', 50259)
- Broken pipe from ('127.0.0.1', 50258)
- Broken pipe from ('127.0.0.1', 50261)
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 41048
"GET /static/vendor/bootstrap/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/vendor/bootstrap-icons/bootstrap-icons.css HTTP/1.1" 304 0
"GET /static/vendor/bootstrap/js/bootstrap.bundle.min.js HTTP/1.1" 304 0
"GET /static/vendor/aos/aos.css HTTP/1.1" 304 0
"GET /static/vendor/swiper/swiper-bundle.min.css HTTP/1.1" 304 0
"GET /static/vendor/swiper/swiper-bundle.min.js HTTP/1.1" 304 0
"GET /static/vendor/aos/aos.js HTTP/1.1" 304 0
"GET /static/js/main.js HTTP/1.1" 304 0
"GET /static/img/tv.png HTTP/1.1" 304 0
"GET /static/css/main.css HTTP/1.1" 304 0
"GET /static/img/post-landscape-1.jpg HTTP/1.1" 304 0
"GET /static/img/post-landscape-2.jpg HTTP/1.1" 304 0
"GET /static/img/post-landscape-3.jpg HTTP/1.1" 304 0
"GET /static/img/post-landscape-5.jpg HTTP/1.1" 304 0
"GET /static/img/post-landscape-6.jpg HTTP/1.1" 304 0
"GET /static/img/post-landscape-7.jpg HTTP/1.1" 304 0
"GET /static/img/post-landscape-8.jpg HTTP/1.1" 304 0
"GET /media/highlights/post-landscape-6_r1pA1YM.webp HTTP/1.1" 304 0
"GET /media/highlights/post-landscape-6.webp HTTP/1.1" 304 0
"GET /media/slider_images/post-slide-2.webp HTTP/1.1" 304 0
"GET /media/slider_images/post-slide-1.webp HTTP/1.1" 304 0
"GET /static/vendor/bootstrap-icons/fonts/bootstrap-icons.woff2?dd67030699838ea613ee6dbda90effa6 HTTP/1.1" 304 0
"GET /media/highlights/post-landscape-1.webp HTTP/1.1" 304 0
"GET /media/blog/post-landscape-5.webp HTTP/1.1" 304 0
"GET /media/blog/post-landscape-3.webp HTTP/1.1" 304 0
"GET /static/img/post-landscape-4.jpg HTTP/1.1" 304 0
"GET /media/slider_images/post-slide-4.webp HTTP/1.1" 304 0
"GET /media/highlights/post-landscape-2.webp HTTP/1.1" 304 0
"GET /media/blog/post-landscape-8.webp HTTP/1.1" 304 0
"GET /media/blog/post-landscape-7.webp HTTP/1.1" 304 0
"GET /media/slider_images/post-slide-3.webp HTTP/1.1" 304 0
"GET /Accounts/Logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 40808
"GET /Tsl/contact/ HTTP/1.1" 200 16175
"POST /Accounts/contact_view HTTP/1.1" 200 56
"GET /Tsl/contact/ HTTP/1.1" 200 16175
"GET /static/vendor/bootstrap/css/bootstrap.min.css.map HTTP/1.1" 304 0
"GET /static/img/favicon.ico HTTP/1.1" 304 0
"POST /Accounts/contact_view HTTP/1.1" 200 56
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Tsl_nigeria\settings.py changed, reloading.
Watching for file changes with StatReloader
- Broken pipe from ('127.0.0.1', 53609)
- Broken pipe from ('127.0.0.1', 53610)
- Broken pipe from ('127.0.0.1', 53612)
- Broken pipe from ('127.0.0.1', 53621)
- Broken pipe from ('127.0.0.1', 53620)
"GET / HTTP/1.1" 200 40808
"GET /Tsl/contact/ HTTP/1.1" 200 16175
"POST /Accounts/contact_view HTTP/1.1" 200 56
"GET /Tsl/login/ HTTP/1.1" 200 13530
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
"POST /Accounts/send_password_reset/ HTTP/1.1" 200 84
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
"POST /Accounts/send_password_reset/ HTTP/1.1" 200 84
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Tsl_nigeria\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
"POST /Accounts/send_password_reset/ HTTP/1.1" 200 84
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
Internal Server Error: /Accounts/send_password_reset/
Traceback (most recent call last):
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\postgresql\base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "autorack.proxy.rlwy.net" (35.214.159.182), port 24209 failed: Software caused connection abort (0x00002745/10053)
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\Documents\Projects\Tsl_nigeria\Accounts\views.py", line 99, in send_password_reset_code
    if not User.objects.filter(email=email).exists():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\query.py", line 659, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 316, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 292, in _cursor
    self.ensure_connection()
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 274, in ensure_connection
    with self.wrap_database_errors:
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 275, in ensure_connection
    self.connect()
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\postgresql\base.py", line 277, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Israel\AppData\Local\Programs\Python\Python312\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server at "autorack.proxy.rlwy.net" (35.214.159.182), port 24209 failed: Software caused connection abort (0x00002745/10053)
	Is the server running on that host and accepting TCP/IP connections?

"POST /Accounts/send_password_reset/ HTTP/1.1" 500 145
"GET /Tsl/send_password/ HTTP/1.1" 200 14025
"POST /Accounts/send_password_reset/ HTTP/1.1" 200 84
Watching for file changes with StatReloader
- Broken pipe from ('127.0.0.1', 53535)
- Broken pipe from ('127.0.0.1', 53534)
- Broken pipe from ('127.0.0.1', 53543)
- Broken pipe from ('127.0.0.1', 53544)
- Broken pipe from ('127.0.0.1', 53547)
- Broken pipe from ('127.0.0.1', 53548)
- Broken pipe from ('127.0.0.1', 53549)
"GET / HTTP/1.1" 200 40808
"GET /Tsl/live_tv/ HTTP/1.1" 200 22636
"GET /Tsl/ondemand/ HTTP/1.1" 200 23993
"GET /media/event_images/event_images/post-slide-3.webp HTTP/1.1" 304 0
"GET /media/highlight_images/post-slide-4.webp HTTP/1.1" 304 0
"GET /media/showcase_images/showcase_images/post-slide-2.webp HTTP/1.1" 304 0
"GET /media/media_section/media_section/post-slide-4.webp HTTP/1.1" 304 0
"GET /Tsl/About/ HTTP/1.1" 200 13086
"GET /static/img/team/team-1.jpg HTTP/1.1" 304 0
"GET /static/img/team/team-2.jpg HTTP/1.1" 304 0
"GET /static/img/team/team-3.jpg HTTP/1.1" 304 0
"GET /Tsl/contact/ HTTP/1.1" 200 16175
- Broken pipe from ('127.0.0.1', 52580)
"GET /Tsl/home/ HTTP/1.1" 200 40808
"GET /Tsl/ondemand/ HTTP/1.1" 200 23973
"GET /Tsl/ondemand/ HTTP/1.1" 200 23770
"GET /Tsl/contact/ HTTP/1.1" 200 16175
"GET /Tsl/home/ HTTP/1.1" 200 40305
"GET /Tsl/live_tv/ HTTP/1.1" 200 22636
"GET /Tsl/ondemand/ HTTP/1.1" 200 23770
C:\Users\Israel\Documents\Projects\Tsl_nigeria\Tsl_nigeria\settings.py changed, reloading.
